// <auto-generated />
namespace ProfileSelect.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _3_03072019 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_3_03072019));
        
        string IMigrationMetadata.Id
        {
            get { return "201907032148302_3_03072019"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
